### ISSUE TITLE
Twilio lib incompatible with newer jackson library (ver > 2?)

### ISSUE THREAD

**Issue by amiramit** [twilio/twilio-java#128]
Happens in google app engine.
SMS send successes, but still client get the following exception:

Caused by: java.lang.ClassNotFoundException: 
org.codehaus.jackson.JsonParseException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:216)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 58 more

**Comment by Saheb** [comment]
Any updates on this issue? I am still facing it. 
Or any temporary solutions or hacks around this?

**Comment by mmistretta** [comment]
im facing this issue as well.  Any work around?

**Comment by carlosdp** [comment]
Fixed by #231
