### ISSUE TITLE
IncomingPhoneNumber's getVoiceCallerIdLookup returns Object, not String

### ISSUE THREAD

**Issue by alexanderdean** [twilio/twilio-java#198]
In `IncomingPhoneNumber.java`:

```scala
	/**
	 * Gets the voice caller id lookup.
	 *
	 * @return the voice caller id lookup
	 */
	public String getVoiceCallerIdLookup() {
		return this.getProperty("voice_caller_id_lookup");
	}
```

But calling it gives:

```
java.lang.IllegalArgumentException: Property voice_caller_id_lookup is an object.  Use getObject() instead.
	at com.twilio.sdk.resource.InstanceResource.getProperty(InstanceResource.java:112)
	at com.twilio.sdk.resource.instance.IncomingPhoneNumber.getVoiceCallerIdLookup(IncomingPhoneNumber.java:232)
```

**Comment by jingming** [comment]
Associated PRs are merged.
