### ISSUE TITLE
4.4.1: Application.getDateCreated() / .getDateUpdated() throws a NoSuchMethod exception

### ISSUE THREAD

**Issue by 4np** [twilio/twilio-java#212]
In version ```4.4.1``` of the SDK calling ```getDateUpdated()``` or ```getDateCreated()``` on a ```Application``` will result in a ```NoSuchMethodException```:

```
java.lang.NoSuchMethodError: org.apache.commons.lang3.time.FastDateFormat.parse(Ljava/lang/String;)Ljava/util/Date;
	at com.twilio.sdk.resource.InstanceResource.parseDate(InstanceResource.java:189)
	at com.twilio.sdk.resource.InstanceResource.getDateProperty(InstanceResource.java:136)
	at com.twilio.sdk.resource.instance.Application.getDateUpdated(Application.java:120)
	... program code ...
```

Example source:

```java
        // get the application by application SID
        Application application = getRestClient().getAccount().getApplication(applicationSID);
        application.getDateUpdated();
```

**Comment by skimbrel** [comment]
I can't reproduce this one either… given that the `NoSuchMethodError` is originating from way over in `org.apache.commons.lang3.time` can you see what version of that you have installed?
