### ISSUE TITLE
RuntimeExceptions are not properly handled by TwilioClient's safeRequest method 

### ISSUE THREAD

**Issue by rustamli** [twilio/twilio-java#221]
It seems [`safeRequest()`](https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/sdk/TwilioClient.java#L502) method in the `TwilioClient` class doesn't properly handle [`RuntimeExceptions`](https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/sdk/TwilioClient.java#L390) thrown by the `request()` method

Keep getting the following exception few times a day, which shouldn't be possible considering the retries logic in the `safeRequest()` method (it seems retries don't work): 

```
java.lang.RuntimeException: java.io.IOException: Error flushing content in Google App Engine fetch
	at com.twilio.sdk.TwilioClient.request(TwilioClient.java:390)
	at com.twilio.sdk.TwilioClient.safeRequest(TwilioClient.java:507)
	at com.twilio.sdk.TwilioClient.safeRequest(TwilioClient.java:489)
	at com.twilio.sdk.resource.Resource.load(Resource.java:50)
	at com.twilio.sdk.resource.ListResource.getPageData(ListResource.java:189)
	at com.twilio.sdk.resource.ListResource.iterator(ListResource.java:75)
	at ox.base.util.TwilioUtils.accountByNs(TwilioUtils.java:126)
```

**Comment by rustamli** [comment]
This seems related to issues #189 and #94

**Comment by jingming** [comment]
We have introduced a new suite of exceptions in `7.0.0` to avoid having to throw the base `RuntimeException`.
