### ISSUE TITLE
NPE in XmlResponseParser

### ISSUE THREAD

**Issue by ajstokar** [twilio/twilio-java#224]
It seems as though the XML is no longer returning the NUM_PAGES_KEY which is causing this exception. Please let me know what we are supposed to do here. Anyone using your Java SDK library will have the same issue.

java.lang.NullPointerException
    at com.twilio.sdk.parser.XmlResponseParser.parseXml(XmlResponseParser.java:97)
    at com.twilio.sdk.parser.XmlResponseParser.parse(XmlResponseParser.java:27)
    at com.twilio.sdk.TwilioRestResponse.toMap(TwilioRestResponse.java:245)
    at com.twilio.sdk.resource.ListResource.parseResponse(ListResource.java:205)
    at com.twilio.sdk.resource.Resource.load(Resource.java:52)
    at com.twilio.sdk.resource.ListResource.getPageData(ListResource.java:189)
    at com.twilio.sdk.resource.ListResource.iterator(ListResource.java:75)
    at

Sample Response that we see today (no numpages or total attributes)

<UsageRecords end="0" firstpageuri="/2010-04-01/Accounts/ACaa8e363579f51d33b5aa1b778b4c9e46/Usage/Records.xml?Category=sms&amp;StartDate=2015-08-14&amp;EndDate=2015-09-13&amp;PageSize=50&amp;Page=0" nextpageuri="" page="0" pagesize="50" previouspageuri="" start="0" uri="/2010-04-01/Accounts/ACaa8e363579f51d33b5aa1b778b4c9e46/Usage/Records.xml?Category=sms&amp;StartDate=2015-08-14&amp;EndDate=2015-09-13&amp;PageSize=50&amp;Page=0">

**Comment by Ragil** [comment]
Hi ajstokar,

Can you please verify if this is still an issue with version 5.0.0
