### ISSUE TITLE
Sample code from the doc don't work 

### ISSUE THREAD

**Issue by Driox** [twilio/twilio-java#296]
**Version: com.twilio.sdk -> twilio 7.0.0-rc-22 **
**API Subdomain (api):**

### Code Snippet
```java
       private static Message sendMessage(String to, String msg) {
		Twilio.init(ACCOUNT_SID, AUTH_TOKEN);

		PhoneNumber to_number = new PhoneNumber(to);
		PhoneNumber from_number = new PhoneNumber("+33756797465");

		Message message = Message.create(
				to_number, // TO number
				from_number, // From Twilio number
				msg
				).execute();

		return message;
	}

// elsewhere 
TwilioService.sendMessage("+33679559421", "yolo");
```

### Exception / Log
```
java.lang.NoSuchMethodError: org.apache.http.client.methods.RequestBuilder.setCharset(Ljava/nio/charset/Charset;)Lorg/apache/http/client/methods/RequestBuilder;
	at com.twilio.http.NetworkHttpClient.makeRequest(NetworkHttpClient.java:64)
	at com.twilio.http.HttpClient.reliableRequest(HttpClient.java:38)
	at com.twilio.http.HttpClient.reliableRequest(HttpClient.java:22)
	at com.twilio.http.TwilioRestClient.request(TwilioRestClient.java:42)
	at com.twilio.rest.api.v2010.account.MessageCreator.execute(MessageCreator.java:307)
	at com.twilio.rest.api.v2010.account.MessageCreator.execute(MessageCreator.java:25)
	at com.twilio.base.Creator.execute(Creator.java:45)
	at services.twilio.TwilioService.sendMessageUnsafe(TwilioService.java:35)
	at services.twilio.TwilioService.sendMessage(TwilioService.java:17)
	at controllers.Application.test(Application.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:527)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:478)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:454)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:449)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:326)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:303)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	
```

### Steps to Reproduce
1. we use play framework 1.4 with java 8 
2. I just use the sample from the doc https://www.twilio.com/docs/libraries/java#installation-nextgen

**Comment by jingming** [comment]
Hi @Driox! 
Can you provide your other dependencies? I'm concerned this might be an issue related to importing a version of `RequestBuilder` that does not support `setCharset`.

**Comment by Driox** [comment]
```
    - play
    - play -> crud
    - com.google.guava -> guava 18.0
    - org.apache.httpcomponents -> httpcore 4.3.2 : 
        force: true
    - org.apache.httpcomponents -> httpclient 4.3.4 :
        force: true

    - com.amazonaws -> aws-java-sdk 1.3.0

    - play -> fbgraph 0.4 :
        transitive: false


    - org.seleniumhq.selenium -> selenium-java 2.47.1:
        exclude:
          - io.netty -> *

    - com.codeborne -> phantomjsdriver 1.2.1:
        exclude:
          - org.seleniumhq.selenium -> *
          - org.seleniumhq.selenium -> *

    - fr.opensagres.xdocreport -> fr.opensagres.xdocreport.core 1.0.5
    - fr.opensagres.xdocreport -> fr.opensagres.xdocreport.document.docx 1.0.5
    - fr.opensagres.xdocreport -> fr.opensagres.xdocreport.template.freemarker 1.0.5
    - fr.opensagres.xdocreport -> fr.opensagres.xdocreport.template.velocity 1.0.5
    - fr.opensagres.xdocreport -> org.apache.poi.xwpf.converter.pdf 1.0.5
    - commons-fileupload -> commons-fileupload [1.2.1, )
    - commons-io -> commons-io [1.3.2, )
    - org.apache.sanselan -> sanselan 0.97-incubator
    - play -> logisimayml 1.8
    - com.mixpanel -> mixpanel-java 1.3.0
    - com.googlecode.owasp-java-html-sanitizer -> owasp-java-html-sanitizer [r232,)
    - org.owasp.antisamy -> antisamy 1.5.3
    - com.newrelic.agent.java -> newrelic-api [3.12.0,)
    - org.codehaus.jackson -> jackson-core-asl 1.9.11
    - org.codehaus.jackson -> jackson-mapper-asl 1.9.11
    - org.apache.xmlrpc -> xmlrpc 3.1.3
    - org.apache.xmlrpc -> xmlrpc-client 3.1.3

    # deps for editing the google sheet's message
    - com.google.api-client -> google-api-client 1.21.0
    - com.fasterxml.jackson.core -> jackson-core 2.1.3
    - com.google.oauth-client -> google-oauth-client 1.21.0
    - com.google.http-client -> google-http-client-jackson2 1.20.0
    - com.google.http-client -> google-http-client-jackson 1.20.0
    - google -> gdata-base 1.0
    - google -> gdata-client 1.0
    - google -> gdata-client-meta 1.0
    - google -> gdata-core 1.0
    - google -> gdata-spreadsheet 3.0
    - google -> gdata-spreadsheet-meta 3.0
    - com.twilio.sdk -> twilio-java-sdk (6.0,6.9)

    # Used to convert HTML mail into plain text
    - org.jsoup -> jsoup 1.8.3
```

**Comment by jingming** [comment]
@Driox I think `org.apache.httpcomponents -> httpclient 4.3.4` is the problem. It looks like `setCharset` was introduced in `httpclient 4.4` and we are using `4.5.2`. 

Consider updating your `httpclient` dependency to resolve this issue.

**Comment by aahtesham** [comment]
i have seen same issue via Spring then upgrade your httpClient its Looking amazing

**Comment by JevPrentice** [comment]
Thanks @jingming and @Driox I was experiencing the same issue on vert.x - This has resolved my issue!

**Comment by gvitjain** [comment]
Upgrading org.apache.httpcomponents -> httpclient 4.5.4 will resolve this issue
