### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by venwyhk** [twilio/twilio-java#299]
> mvn install

StackTrace:

`Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.359 sec <<< FAILURE!
testRfc2822(com.twilio.converter.DateConverterTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException
        at com.twilio.converter.DateConverterTest.testRfc2822(DateConverterTest.java:17)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java
:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.jav
a:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
`

**Comment by tmconnors** [comment]
@venwyhk are you still encountering this problem? - we have had two subsequent releases.

If this is a blocker try: `mvn install -DskipTests` to avoid running the tests.

**Comment by jingming** [comment]
Closing due to lack of response, feel free to open if the issue is still happening.
