### ISSUE TITLE
java.util.NoSuchElementException on Arraylist

### ISSUE THREAD

**Issue by Fabrizio133** [twilio/twilio-java#325]
```java
  public void startStackTask()
  {
    new BukkitRunnable()
    {
      public void run()
      {
    	
        int i = MobStackModul.this.getInstance().getConfigModul().getMobStackingRadius();
        List<EntityType> localList = MobStackModul.this.mobList;
        Iterator localIterator2;
        for (Iterator localIterator1 = Bukkit.getServer().getWorlds().iterator(); localIterator1.hasNext(); localIterator2.hasNext())
        {
          World localWorld = (World)localIterator1.next();
          localIterator2 = localWorld.getLivingEntities().iterator();
          LivingEntity localLivingEntity = (LivingEntity)localIterator2.next();
          if ((localList.contains(localLivingEntity.getType())) && (localLivingEntity.isValid())) {
            for (Entity localEntity : localLivingEntity.getNearbyEntities(i, i, i)) {
              if (((localEntity instanceof LivingEntity)) && (localEntity.isValid()) && (localList.contains(localEntity.getType()))) {
                MobStackModul.this.stackOne(localLivingEntity, (LivingEntity)localEntity, ChatColor.valueOf(MobStackModul.this.getInstance().getConfigModul().getMobStackColor()));
              }
            }
          }
        }
      }
    }.runTaskTimer(getInstance(), 40L, 40L);
  }

java.util.NoSuchElementException
        at java.util.ArrayList$Itr.next(ArrayList.java:854) ~[?:1.8.0_111]
        at com.CoreHCF.Modules.MobStackModul$1.run(MobStackModul.java:85) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
```
Can you help me solve it?

**Comment by jingming** [comment]
@Fabrizio133 Thanks for writing in!

This block of code does not appear to use Twilio. Do you have the portion of code that uses Twilio?
