### ISSUE TITLE
Didn't find class "org.apache.http.client.config.RequestConfig" 

### ISSUE THREAD

**Issue by HazemEngMuh** [twilio/twilio-java#358]
My code as follow:
 ```
 Twilio.init(ACCOUNT_SID, AUTH_TOKEN);

                Message message = Message.creator(
                            new PhoneNumber("+905367705383"),  // To number
                            new PhoneNumber("+17854343244"),  // From number
                           "jhkhjk"
                    ).create();
```
When I run it there is problem 

```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/client/config/RequestConfig;
                                                                           at com.twilio.http.NetworkHttpClient.<init>(NetworkHttpClient.java:33)
                                                                           at com.twilio.http.TwilioRestClient$Builder.build(TwilioRestClient.java:97)
                                                                           at com.twilio.Twilio.getRestClient(Twilio.java:122)
                                                                           at com.twilio.base.Creator.create(Creator.java:45)
                                                                           at .Activities.LoginActivity$1.onClick(LoginActivity.java:80)
                                                                           at android.view.View.performClick(View.java:5265)
                                                                           at android.view.View$PerformClick.run(View.java:21534)
                                                                           at android.os.Handler.handleCallback(Handler.java:815)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                           at android.os.Looper.loop(Looper.java:207)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.client.config.RequestConfig" on path: DexPathList[[zip file "/data/app/-2/base.apk", zip file "/data/app/-2/split_lib_dependencies_apk.apk", zip file "/data/app/k-2/split_lib_slice_0_apk.apk", zip file "/data/app/2/split_lib_slice_1_apk.apk", zip file "/data/app/-2/split_lib_slice_2_apk.apk", zip file "/data/app/2/split_lib_slice_3_apk.apk", zip file "/data/app/-2/split_lib_slice_4_apk.apk", zip file "/data/app-2/split_lib_slice_5_apk.apk", zip file "/data/app/-2/split_lib_slice_6_apk.apk", zip file "/data/app/-2/split_lib_slice_7_apk.apk", zip file "/data/app/-2/split_lib_slice_8_apk.apk", zip file "/data/app2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at com.twilio.http.NetworkHttpClient.<init>(NetworkHttpClient.java:33) 
                                                                           at com.twilio.http.TwilioRestClient$Builder.build(TwilioRestClient.java:97) 
                                                                           at com.twilio.Twilio.getRestClient(Twilio.java:122) 
                                                                           at com.twilio.base.Creator.create(Creator.java:45) 
                                                                           at .Activities.LoginActivity$1.onClick(LoginActivity.java:80) 
                                                                           at android.view.View.performClick(View.java:5265) 
                                                                           at android.view.View$PerformClick.run(View.java:21534) 
                                                                           at android.os.Handler.handleCallback(Handler.java:815) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                           at android.os.Looper.loop(Looper.java:207) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5728) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                       	Suppressed: java.lang.ClassNotFoundException: org.apache.http.client.config.RequestConfig
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                           		... 15 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

how to solve this problem thanks for help

**Comment by jingming** [comment]
@HazemEngMuh Based on the stack trace that you've provided, can I guess that you are trying to use this helper library inside your Android application?

If that is the case, we strongly encourage you to use a different method. By shipping this library inside your application and initializing it, you are exposing your Twilio account credentials to the public which then can be obtained by decompiling your application.

**Comment by ahmadspm** [comment]
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.config.RequestConfig
