### ISSUE TITLE
issue unable to create Message

### ISSUE THREAD

**Issue by SaiKiranDande** [twilio/twilio-java#397]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:** 7.14.0

### Code Snippet
` val message = Message.creator(
                PhoneNumber("+15558881234"),
                PhoneNumber("+15559994321"),
                "Hello world!"
        ).create()
# paste code here
```

### Exception/Log
```
FATAL EXCEPTION   
 Process: com.example.dande.mytwilioapp, PID: 15048                                                                               java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
                                                                                   at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
                                                                                   at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:172)
                                                                                   at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:109)
                                                                                   at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:116)
                                                                                   at com.twilio.http.NetworkHttpClient.<init>(NetworkHttpClient.java:58)
                                                                                   at com.twilio.http.TwilioRestClient$Builder.build(TwilioRestClient.java:102)
                                                                                   at com.twilio.Twilio.getRestClient(Twilio.java:122)
                                                                                   at com.twilio.base.Creator.create(Creator.java:45)
                                                                                   at com.example.dande.mytwilioapp.MainActivity.initMsg(MainActivity.kt:34)
                                                                                   at com.example.dande.mytwilioapp.MainActivity.access$initMsg(MainActivity.kt:12)
                                                                                   at com.example.dande.mytwilioapp.MainActivity$onCreate$1.onClick(MainActivity.kt:21)
                                                                                   at android.view.View.performClick(View.java:5204)
                                                                                   at android.view.View$PerformClick.run(View.java:21153)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

### Steps to Reproduce
1.
2.
3.


### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by jingming** [comment]
@SaiKiranDande Are you trying to run this inside your android application? If so, we highly discourage doing this. By combining this with your android application, it means you are exposing your auth token which can lead to it being stolen.

**Comment by mmamudassir** [comment]
please update about this issue as i am facing too how to fix

**Comment by philnash** [comment]
Hey @MuhammedRef3at,

This is not a bug, the twilio-java library is not intended for use in Android applications. If you were to use it within an Android application you would expose your Application SID and Auth Token. If a malicious user were to discover this, they could abuse your account.

Instead, we recommend that you set up a server from which you send the messages and make requests to that server from your Android application. Check out this post on [sending SMS messages from your Android app](https://www.twilio.com/blog/2016/05/how-to-send-an-sms-from-android.html) for more details.

**Comment by curtlush** [comment]
@philnash I am encountering this issue with a project right now. The android app will only be installed on one device and it will be locked down and encrypted (no concern about exposing SID/Auth token). Is there no way to do this without a backend?

**Comment by philnash** [comment]
@curtlush You could certainly make calls to the Twilio API from an Android device using whatever HTTP client you wish. However this library will not support Android, to avoid making it easy to do this. 

I'm no Android developer I'm afraid, so I don't know where to point you for resources on making HTTP requests from Android, however the [Twilio documentation](http://twilio.com/docs/) has all the URLs, paths and parameters that you'll need to make these requests yourself.
