### ISSUE TITLE
TaskUpdator.update Null Pointer Exception when Http Response Status is 204

### ISSUE THREAD

**Issue by vuquocbao** [twilio/twilio-java#497]
I'm getting a null pointer exception when calling TaskUpdator.update to update a Task in TaskRouter. This happens when the HttpStatus code is a 204. After looking at the source code,  when a response with a 204 comes back a null pointer gets thrown because it is trying to get the stream or contents of the Response which are both null.

Instead of calling content.getBytes directly when getting the InputStream in Response.java, getContent() method should be called instead because it will default to an empty string. 

**Version:** 7.32.0

### Code Snippet
```java
    public InputStream getStream() {
        if (stream != null) {
            return stream;
        }
        try {
            return new ByteArrayInputStream(content.getBytes("utf-8"));
        } catch (final UnsupportedEncodingException e) {
            throw new ApiException("UTF-8 encoding not supported", e);
        }
    }
```

Using content.getBytes is super unsafe here. It seems like the constructor that takes a string argument is only used in Tests. In the main code the InputStream constructor is used. So during real-life operation content is always null.

### Exception/Log
```
java.lang.NullPointerException: null
	at com.twilio.http.Response.getStream(Response.java:82)
	at com.twilio.rest.taskrouter.v1.workspace.TaskUpdater.update(TaskUpdater.java:140)
	at com.porch.switchboard.service.client.twilio.TwilioTaskClient$$anonfun$setTaskStatusToWrapping$2.apply(TwilioTaskClient.scala:49)
	at com.porch.switchboard.service.client.twilio.TwilioTaskClient$$anonfun$setTaskStatusToWrapping$2.apply(TwilioTaskClient.scala:49)
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$4.block(ExecutionContextImpl.scala:48)
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45)
	at scala.concurrent.package$.blocking(package.scala:123)
	at com.porch.switchboard.service.util.FutureContext$$anonfun$blockingFuture$1.apply(FutureContext.scala:20)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at com.porch.scala.dropwizard.asynctracer.TracingRunnableWrapper.run(TracingExecutionContext.scala:61)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### Steps to Reproduce
1. Create Task
2. Update Task (make sure that a 204 is returned)
3. Observe Null pointer exception when trying to deserialize Task object

 Or here is a possible unit test code snippet that will repo the error. I'm passing in null instead of an empty string because NetworkHttpClient will pass in a null value when the HttpResponse is a 204
```java
Response response = new Response(null, TwilioRestClient.HTTP_STATUS_CODE_NO_CONTENT);
Task.fromJson(response.getStream(), client.getObjectMapper());
```

**Comment by childish-sambino** [comment]
Do you have an example where update task API should return 204? Trying to recreate on my end.

**Comment by vuquocbao** [comment]
I was not able to reproduce the issue myself either. I tried send multiple update event one after another. But that always results in 400 or 404s. 

I'm not really sure when or why 204s are happening. My assumption is that it could be a race condition where the server accepts the update event and verifies that that task is updatable. But when it comes time to update it cannot be updated because something moved it to a delete or a un-updatable state since 204s are returned for deletes.

If you can help look into when and why 204s are being return that would be great.

**Comment by Parth-9711** [comment]
Any Update ?

**Comment by childish-sambino** [comment]
@vuquocbao @Parth-9711 Best to [file a support ticket](https://twilio.com/help/contact) in these cases to better understand why 204s are being returned. If you can provide them with a few request IDs they can help to track down what's going on. If it turns out a 204 is the proper status and you're able to reliably recreate this, please re-open so I can see what needs to change in this lib.
