### ISSUE TITLE
   java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by GreenLava786** [twilio/twilio-java#744]
### Code Snippet
```java
# paste code here
``` Twilio.init(ACCOUNT_SID, AUTH_TOKEN);
            val message = Message.creator(
                PhoneNumber("+916395604198"),
                PhoneNumber("+12544707932"),
                "Hi,Bro").create();

            System.out.println(message.sid);

### Exception/Log
```
# paste exception/log here
```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wizion.contactsapp, PID: 3395
    java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes4.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:194)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:116)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:123)
        at com.twilio.http.NetworkHttpClient.<init>(NetworkHttpClient.java:70)
        at com.twilio.http.NetworkHttpClient.<init>(NetworkHttpClient.java:45)
        at com.twilio.http.NetworkHttpClient.<init>(NetworkHttpClient.java:36)
        at com.twilio.http.TwilioRestClient$Builder.build(TwilioRestClient.java:143)
        at com.twilio.Twilio.buildRestClient(Twilio.java:202)
        at com.twilio.Twilio.getRestClient(Twilio.java:174)
        at com.twilio.base.Creator.create(Creator.java:40)
        at com.wizion.contactsapp.ui.main.contacts.MessageComposeActivity.sendSMS(MessageComposeActivity.kt:64)
        at com.wizion.contactsapp.ui.main.contacts.MessageComposeActivity.init$lambda$0(MessageComposeActivity.kt:48)
        at com.wizion.contactsapp.ui.main.contacts.MessageComposeActivity.$r8$lambda$W-TCP6r7k4_B2pHtzQZJCSIytHU(Unknown Source:0)
        at com.wizion.contactsapp.ui.main.contacts.MessageComposeActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7506)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1202)
        at android.view.View.performClickInternal(View.java:7483)
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
        at android.view.View$PerformClick.run(View.java:29334)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)


### Technical details:
* twilio-java version: 9.6.0
* java version:11.0.15

**Comment by shweta-7span** [comment]
Hey @DanielErnestoThompson, Thank you for answer this question. I checked in my project it is using '4.5.13' version for httpClient. I'm still getting this error. Below I put the full error. Please, let me know if anything I'm missing.

Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:116)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:123)
	at com.twilio.http.NetworkHttpClient.<init>(NetworkHttpClient.java:70)
	at com.twilio.http.NetworkHttpClient.<init>(NetworkHttpClient.java:45)
	at com.twilio.http.NetworkHttpClient.<init>(NetworkHttpClient.java:36)
	at com.twilio.http.TwilioRestClient$Builder.build(TwilioRestClient.java:143)
	at com.twilio.Twilio.buildRestClient(Twilio.java:202)
	at com.twilio.Twilio.getRestClient(Twilio.java:174)
	at com.twilio.base.Creator.create(Creator.java:40)
	at com.example.demomaskedcall.Example.main(Example.java:29)

**Comment by GreenLava786** [comment]
I have made a custom API call using Retrofit to send SMS and receive an SMS list."
You can check this at: https://github.com/waseem-i7/Contact-App. If you don't understand anything, please let me know.

**Comment by AsabuHere** [comment]
Hi @GreenLava786 I tested the code pasted in the thread, with twilio-java version 9.6.0 and java version 11.0.19 and this is working for me. Here is the configuration details for my project
<groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.5.13</version>

and 

<groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpcore</artifactId>
      <version>4.4.13</version>

**Comment by AsabuHere** [comment]
Hi @GreenLava786 and @shweta-7span Are you trying to run this inside your android application?

**Comment by shweta-7span** [comment]
Yes, I made the "Example.Java" class inside the app folder of android app project and run it with "Coverage". I will do from the above blog which you shared. 

Thank you :smiley:

**Comment by AsabuHere** [comment]
Hi @GreenLava786, Closing this issue since twilio-java library is not intended for use in Android applications.

@sharunthomas Please open a new issue with the details of the environment and use case to track this
