### ISSUE TITLE
Latest Twilio Java SDK breaks Job endpoint

### ISSUE THREAD

**Issue by ukby1234** [twilio/twilio-java#748]
### Issue Summary
Job.fetcher(jobSid).fetch failed with the exceptions posted. 

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```java
Job.fetcher(jobSid).fetch
```

### Exception/Log
```
Exception in thread "main" com.twilio.exception.ApiException: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.String,java.lang.Object>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (ByteArrayInputStream); line: 1, column: 348] (through reference chain: com.twilio.rest.bulkexports.v1.export.Job["details"])
	at com.twilio.rest.bulkexports.v1.export.Job.fromJson(Job.java:84)
	at com.twilio.rest.bulkexports.v1.export.JobFetcher.fetch(JobFetcher.java:61)
	at com.twilio.rest.bulkexports.v1.export.JobFetcher.fetch(JobFetcher.java:30)
	at com.twilio.base.Fetcher.fetch(Fetcher.java:40)
```

### Technical details:
* twilio-java version: 9.6.2
* java version: 11

**Comment by ukby1234** [comment]
@kridai any updates on this bug?

**Comment by sbansla** [comment]
@ukby1234 I am actively working on the fix of above issue. Will be updating soon.

**Comment by sbansla** [comment]
@ukby1234 I tried calling the API using Postman, and it turns out that the '**details**' should be an array of hashmaps instead of a single hashmap. This appears to be a bug in how the API specifications are declared, which is why the SDK is currently using it as a hashmap. I will work to rectify this issue internally and will inform you once it is resolved.

**Comment by sbansla** [comment]
I have again reminded the concerned team.

**Comment by ukby1234** [comment]
@sbansla any updates on this issue?

**Comment by tiwarishubham635** [comment]
Hi! This issue has been fixed and released in the RC branch [11.0.0-rc](https://github.com/twilio/twilio-java/tree/11.0.0-rc). We are in process of releasing the major version 11.0.0 soon and it will be a part of that. Thanks!
